- name: Hello World Sample
  hosts: sang-test-1
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Download benchmark vm file
      get_url:
        url: https://raw.githubusercontent.com/nhanhoadocs/scripts/master/Utilities/bench_vm.sh
        dest: /home/ubuntu/bench_vm.sh
        mode: '0777'
    - name: Execute the script
      command: sh /home/ubuntu/bench_vm.sh