- name: Hello World Sample
  hosts: sang-test-1
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Download benchmark vm file
      get_url:
        url: https://raw.githubusercontent.com/nhanhoadocs/scripts/master/Utilities/bench_vm.sh
        dest: /home/ubuntu/bench_vm.sh
        mode: '0777'
    - name: Run a script with arguments 
       ansible.builtin.script: /home/ubuntu/bench_vm.sh